=== hortelanobruno/brunouade/trunk/ZaraCentroDeDistribucionCliente/xml/zaraSchema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="solicituddistribucion">
         <xsd:complexType>
            <xsd:sequence>
                 <xsd:element name="numero" type="xsd:integer"/>
                 <xsd:element name="tienda" type="Tienda"/>
                 <xsd:element name="articulosropa" type="aRopa"/>
				 <xsd:element name="articuloshogar" type="aHogar"/>
            </xsd:sequence>
        </xsd:complexType>
   </xsd:element>

   <xsd:complexType name="articulo">
   		<xsd:sequence>
   			<xsd:element name="codigo" type="xsd:integer"/>
	   		<xsd:element name="cantidad" type="xsd:integer"/>
   		</xsd:sequence>
   </xsd:complexType>
   
    <xsd:complexType name="Tienda">
     	<xsd:sequence>
     		<xsd:element name="codigoTienda" type="xsd:integer"/>
     		<xsd:element name="nombreTienda" type="xsd:string"/>
     	</xsd:sequence>
     </xsd:complexType>  
     
     <xsd:complexType name="aRopa">
     	<xsd:sequence>
     		<xsd:element maxOccurs="60" minOccurs="1" name="articuloropa" type="articulo"/>
    	</xsd:sequence>
 	 </xsd:complexType>
 	 
 	 <xsd:complexType name="aHogar">
     	<xsd:sequence>
     		 <xsd:element maxOccurs="60" minOccurs="1" name="articulohogar" type="articulo"/>
    	</xsd:sequence>
 	 </xsd:complexType>
 	     
</xsd:schema>

=== hortelanobruno/brunouade/ZaraCentroDeDistribucionCliente/xml/SolDist.xml
<solicituddistribucion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zaraSchema.xsd">

	<numero>1000</numero>

	<tienda>
		<codigoTienda>1</codigoTienda>
		<nombreTienda>Florida</nombreTienda>
	</tienda>

	<articulosropa>
		<articuloropa>
			<codigo>1000</codigo>
			<cantidad>50</cantidad>
		</articuloropa>
		<articuloropa>
			<codigo>1001</codigo>
			<cantidad>20</cantidad>
		</articuloropa>

	</articulosropa>
</solicituddistribucion>
